version: '3'

services:
  server:
    build: ./server-go
    ports:
      - "8080:5000"
    environment:
      - GEMINI_API_KEY=AIzaSyC0YmoIZXgzdU34KV8zyFWniCO-CnSTpKY

  client:
    build: ./client-js
    ports:
      - "3000:80"
    depends_on:
      - server
